# Generated by Django 2.2.7 on 2020-02-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennclubslite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='club',
            new_name='clubs',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(to='pennclubslite.Club'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
